### ISSUE TITLE
Does not finish verilator compilation with verilator v4.210-2

### ISSUE THREAD

**Issue by Moggel12** [mupq/pqriscv-vexriscv#4]
When instantiating a blank CPU with `sbt "runMain mupq.PQVexRiscvSim --ram 256,128"` the verilator compilation ends with a stacktrace and an error, the error seems to be the same no matter the flags given when running. This also occurs when using the other targets available.
I have had success with v4.102-1 but have not tried any higher versions.
I use sbt v1.5.5 and Java 8.

**Comment by rpls** [comment]
Yeah, there are some bugs comming and going with verilator. I'll try to push an vexriscv update, maybe it'll help. The upstream SpinalHDL hase some patches for Verilator.

**Comment by rpls** [comment]
Try this one now. Works for me on Verilator v4.210 and Java 8.

**Comment by Moggel12** [comment]
Seems to work on my machine as well (same Java and verilator version as you), although I get a few errors during Scala compilation. The latter might just be something with my SBT setup and does not seem to affect functionality currently.
