### ISSUE TITLE
A dependency downloading error

### ISSUE THREAD

**Issue by lkcp** [mupq/pqriscv-vexriscv#5]
Hi,

When I ran this project, I get a dependency downloading error 

> [error] sbt.librarymanagement.ResolveException: Error downloading default:vexriscv_2.11:0.1.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/julian/.ivy2/localdefault/vexriscv_2.11/0.1.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/default/vexriscv_2.11/0.1.0-SNAPSHOT/vexriscv_2.11-0.1.0-SNAPSHOT.pom

When I entered the url, I get a "404Not found", and I didn't find a configure file including this url, how can I fix this error?

Thanks.

**Comment by Moggel12** [comment]
Did you manage to resolve this?

**Comment by rpls** [comment]
Sorry for the long delay, I'm finally getting around to maintaining this project again.

It should be fixed now, I guess at some point SBT changed its URL format for the GIT dependency.
